#!/bin/bash -e
unamestr=$(uname)
if [[ "$unamestr" == 'Linux' ]]; then # Linux
  DIR=$(dirname $(readlink -f $0))
elif [[ "$unamestr" == "Darwin" ]]; then # Mac
  cmd=$(which "$0")
  if [ -L "$cmd" ]; then
    cmd=$(readlink "$cmd")
  fi
  DIR=$(dirname "$cmd")
else
  echo "Only Linux and Mac OS X are supported!"
  exit
fi

# Python の環境をqira独自のものに virtual_env 使用
unset PYTHONPATH
source $DIR/venv/bin/activate
exec /usr/bin/env python2.7 $DIR/middleware/qira.py $*
